---
abstract: 'provides ''$self' in OO code.'
author:
  - 'Kang-min Liu  C<< <gugod@gugod.org> >>'
build_requires:
  Test::More: 0.42
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: self
name: self
no_index:
  directory:
    - inc
    - t
    - examples
requires:
  B::Hooks::Parser: 0.08
  B::OPCheck: 0.27
  Sub::Exporter: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.31
